/**
 * A spore that slows down an insect when consumed, halving its action points for a duration.
 * Inherits core spore attributes (type, location, owner, id, nutrition) from the Spore base class.
 */
public class SlowingSpore extends Spore {

    /**
     * Constructs a SlowingSpore at the specified location with the given owner and ID.
     *
     * @param onTekton the Tekton on which this spore is placed
     * @param owner    the Mushroomer player who owns this spore
     * @param id       the unique identifier for this spore instance
     */
    public SlowingSpore(Tekton onTekton, Mushroomer owner, int id) {
        super(SporeType.SLOWING, onTekton, owner, id, 5);
    }

    /**
     * Constructs a SlowingSpore at the specified location with the given owner.
     * ID will be auto-generated by the Spore base class when 0 is passed.
     *
     * @param tekton    the Tekton on which this spore is placed
     * @param owner     the Mushroomer player who owns this spore
     */
    public SlowingSpore(Tekton tekton, Mushroomer owner) {
        super(SporeType.SLOWING, tekton, owner, 0, 5);
    }

    /**
     * Applies the slowing effect to the specified insect.
     *
     * @param insect the insect being affected by this spore
     */
    @Override
    public void affectInsect(Insect insect) {
        insect.effectedBySlowingSpore();
    }
}