/**
 * A spore that speeds up an insect when consumed, doubling its action points for a duration.
 * Inherits core spore attributes (type, location, owner, id, nutrition) from the Spore base class.
 */
public class SpeedingSpore extends Spore {

    /**
     * Constructs a SpeedingSpore at the specified location with the given owner and ID.
     *
     * @param onTekton the Tekton on which this spore is placed
     * @param owner    the Mushroomer player who owns this spore
     * @param id       the unique identifier for this spore instance
     */
    public SpeedingSpore(Tekton onTekton, Mushroomer owner, int id) {
        super(SporeType.SPEEDING, onTekton, owner, id, 5);
    }

    /**
     * Constructs a SpeedingSpore at the specified location with the given owner.
     * ID will be auto-generated by the Spore base class when 0 is passed.
     *
     * @param tekton    the Tekton on which this spore is placed
     * @param owner     the Mushroomer player who owns this spore
     */
    public SpeedingSpore(Tekton tekton, Mushroomer owner) {
        super(SporeType.SPEEDING, tekton, owner, 0, 5);
    }

    /**
     * Applies the speeding effect to the specified insect.
     *
     * @param insect the insect being affected by this spore
     */
    @Override
    public void affectInsect(Insect insect) {
        insect.effectedBySpeedingSpore();
    }
}